// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEvVTNsD6MJj589-1htbiQtxp7GgWNpQ',
    appId: '1:176801141419:web:3bb03a54d562b427969dee',
    messagingSenderId: '176801141419',
    projectId: 'proyecto2-eb96e',
    authDomain: 'proyecto2-eb96e.firebaseapp.com',
    storageBucket: 'proyecto2-eb96e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZdDIF8JLZLRc3uS74M43qRvHdX6z3Gg',
    appId: '1:176801141419:android:6cc70357fafc1c81969dee',
    messagingSenderId: '176801141419',
    projectId: 'proyecto2-eb96e',
    storageBucket: 'proyecto2-eb96e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcJpsXuaQgEgj324p0AOFxGSirFJWk5AU',
    appId: '1:176801141419:ios:46921462c537c998969dee',
    messagingSenderId: '176801141419',
    projectId: 'proyecto2-eb96e',
    storageBucket: 'proyecto2-eb96e.appspot.com',
    iosClientId: '176801141419-e5grtpu6de85a6g94n51ft672p0v7cn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400617',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcJpsXuaQgEgj324p0AOFxGSirFJWk5AU',
    appId: '1:176801141419:ios:46921462c537c998969dee',
    messagingSenderId: '176801141419',
    projectId: 'proyecto2-eb96e',
    storageBucket: 'proyecto2-eb96e.appspot.com',
    iosClientId: '176801141419-e5grtpu6de85a6g94n51ft672p0v7cn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto219400617',
  );
}
